### ISSUE TITLE
как запустить aml_autoscript?

### ISSUE THREAD

**Issue by pichenka007gd** [EvgeniyBlinov/awesome-android-tv-boxes-linux#1]
у меня при попытке через обновление система видит только *.zip файлы для обновления но если я сам добавлю .zip к скрипт/скрипт.cmd то все заканчивается одной ошибкой
![photo_2024-10-10_19-56-16](https://github.com/user-attachments/assets/8c94425d-7c2e-4094-b494-729df85e4d53)

**Comment by EvgeniyBlinov** [comment]
https://github.com/EvgeniyBlinov/awesome-android-tv-boxes-linux/blob/main/FAQ_ru.md#%D0%BA%D0%B0%D0%BA-%D0%BF%D1%80%D0%BE%D0%B8%D1%81%D1%85%D0%BE%D0%B4%D0%B8%D1%82-%D0%B4%D0%B5%D1%84%D0%BE%D0%BB%D1%82%D0%BD%D0%B0%D1%8F-%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0-android-%D0%BD%D0%B0-tv-box-%D0%BE%D1%82-%D0%B2%D0%B5%D0%BD%D0%B4%D0%BE%D1%80%D0%B0-%D0%BD%D0%B0-amlogic-s89xx
